DATA_DIR = 'static/images/database/'
SRC_DATA_DIR = 'src/static/images/database'
OUTPUT_DIR = DATA_DIR + "/output.csv"
IMAGE_DIR = DATA_DIR + '/test_images/'
IMAGE_SRC_DIR = SRC_DATA_DIR + '/test_images/'
IRMA_DIR = SRC_DATA_DIR + '/irma_data'
DATABASE_PATH = DATA_DIR
INDEX_PATH = os.path.join('src', 'static', 'output.csv')
QUERY = os.path.join('static', 'images', 'query')
TEMPLATES = os.path.join('templates')